"""Fix relationships in Task and Comment models

Revision ID: 22f85b275dcc
Revises: 96ff86f9bbb7
Create Date: 2024-08-04 18:57:50.571459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22f85b275dcc'
down_revision: Union[str, None] = '96ff86f9bbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
