"""Fix relationships in Task and Comment models2

Revision ID: ae53b0449f88
Revises: 22f85b275dcc
Create Date: 2024-08-04 19:03:20.586145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae53b0449f88'
down_revision: Union[str, None] = '22f85b275dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
