"""Fix relationships in Task and Comment models 04

Revision ID: b97b9dd5b27c
Revises: 5c5c4ce156f4
Create Date: 2024-08-04 19:21:14.223086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b97b9dd5b27c'
down_revision: Union[str, None] = '5c5c4ce156f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
